cloud:
  aws:
    credentials:
      access-key: AKIAV5MC2RQQYEYSNKMH
      secret-key: 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
    region:
      static: us-west-2
    stack:
      auto: false

application:
  bucket:
    name: owaisnaimstorage

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090